title: Nan Yan
description: >-
  Nan Yan is a PhD student at Northwestern University studying RSI and AI agent
  security and exploring AI for Science (AI4Science).
url: https://lunan0320.github.io
baseurl: ""
lang: en
social_image: /images/social-preview.jpg

owner:
  name: Nan Yan
  avatar: photo/photo1.jpg
  email: nanyan@u.northwestern.edu
  github: lunan0320
  linkedin: nan-yan-31a26837a
  scholar: https://scholar.google.com.hk/citations?user=q-18YfAAAAAJ

google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"
analytics:
  google: G-T5N5JY1E21
  counter: 4c8f7caa-2b55-46cd-a995-2c4633303773

links:
  - title: About
    url: /#about
  - title: Publications
    url: /#publications
  - title: Experience
    url: /#experience
  - title: Honors
    url: /#honors

timezone: America/Chicago
future: true
highlighter: rouge
markdown: kramdown
permalink: /:categories/:title

kramdown:
  input: GFM
  auto_ids: true
  entity_output: as_char

exclude:
  - .idea
  - .bundle
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - assets/less
